#!/usr/bin/env ruby

command = ARGV.shift

case command
when "write"
  file_path = ARGV.shift
  if file_path.nil?
    puts "ERROR: FILE_PATH argument is required"
    exit 1
  end
else
  puts "ERROR: Unknown command #{command}"
  exit 1
end
