#!/usr/bin/env ruby
require "securerandom"

command = ARGV.shift

case command
when "write"
  file_path = ARGV.shift
  if file_path.nil?
    puts "ERROR: FILE_PATH argument is required"
    exit 1
  end
when "read"
  file_path = ARGV.shift
  if file_path.nil?
    puts "ERROR: FILE_PATH argument is required"
    exit 1
  end
when "setup"
  if File.exist?("invisible_ink.key")
    puts "ERROR: invisible_ink.key already exists"
    exit 1
  else
    key = SecureRandom.hex(16)
    File.write("invisible_ink.key", key)
  end
else
  puts "ERROR: Unknown command #{command}"
  exit 1
end
